language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

branches:
  only:
    - master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - codesmoo@gmail.com

before_deploy:
  - zip -r demospringboard *
  - mkdir -p deploy
  - mv demospringboard.zip deploy/demospringboard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: codesmoo/demospringboard #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-deploy # S3 버킷
    key: deploy/demospringboard.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: webservice # CodeDeploy 어플리케이션
    deployment_group: webservice-deploy-group # CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: codesmoo/demospringboard #Github 주소
      branch: master